name: CI

on:
  push:
    #branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'

  pull_request:
    #branches: [main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - 'examples/**'

jobs:

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'
          check-latest: true


      - name: Build
        run: go build -o terraform-provider-virtualbox

      - name: Run go vet
        run: go vet ./...

      - name: Install VirtualBox
        run: sudo apt-get install virtualbox

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        run: golint ./...

      #- name: Run tests
      #  run: go test -race -vet=off ./internal/provider

      - name: test
        run: mkdir -p ~/.terraform.d/plugins/terraform-virtualbox.local/virtualboxprovider/virtualbox/1.0.0/linux_amd64
      
      - name: dir
        run: cp terraform-provider-virtualbox ~/.terraform.d/plugins/terraform-virtualbox.local/virtualboxprovider/virtualbox/1.0.0/linux_amd64

      - uses: actions/setup-go@v1
        with:
          go-version: 1.21
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ~1.3
          terraform_wrapper: false   
      - name: Download Go Modules
        working-directory: terraform-unit-testing
        run: go mod download
      - name: Run Go Test1
        working-directory: terraform-unit-testing
        run: go test -v vpc_test.go -tags=unit
      - name: Run Go Test2
        working-directory: terraform-unit-testing
        run: go test -v vm_test.go -tags=unit