name: Unit Tests
on: push
jobs:
  go-tests:
    name: Run Terratest Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: JosiahSiegel/action-connect-ovpn@v2.0.2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.21
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ~1.3
          terraform_wrapper: false   
      - name: Download Go Modules
        working-directory: terraform-unit-testing
        run: go mod download
      - name: Run Go Test1
        working-directory: terraform-unit-testing
        run: go test -v vpc_test.go -tags=unit
      - name: Run Go Test2
        working-directory: terraform-unit-testing
        run: go test -v vm_test.go -tags=unit