name: Terraform Provider Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:20.10.8
        options: --privileged

    steps:
    - name: Set up Docker Buildx
      run: docker buildx create --use
      
    - name: Build Docker image
      run: docker build -t my-terraform-tests .
      working-directory: .
      
    - name: Run Terratest
      run: docker run my-terraform-tests go test -v ./terraform-unit-testing/